/**
 * @cox/core — FROZEN CONTRACTS
 *
 * Every other package imports ONLY from @cox/core. Cross-package imports are
 * forbidden; the CLI package wires concrete implementations together at the
 * composition root.
 *
 * ⚠️ Builder agents: do NOT edit this file. If a contract blocks you, append
 * an entry to /INTEGRATION-NOTES.md and code around it locally. The
 * integrator resolves contract changes.
 */

// ---------------------------------------------------------------------------
// Tiers, models, providers
// ---------------------------------------------------------------------------

/** Routing tier. Config maps each tier to a concrete model (+ fallbacks). */
export type Tier = "scout" | "builder" | "architect";

export const TIERS: readonly Tier[] = ["scout", "builder", "architect"];

/** A concrete model on a concrete provider. */
export interface ModelRef {
  /** Provider adapter id, e.g. "anthropic", "xai", "openai-compat:local". */
  provider: string;
  /** Provider-native model id, e.g. "claude-sonnet-5", "grok-4-1-fast". */
  model: string;
}

export function modelKey(ref: ModelRef): string {
  return `${ref.provider}/${ref.model}`;
}

/** Tier → primary model + ordered fallbacks (tried on provider errors). */
export interface TierMap {
  scout: { primary: ModelRef; fallbacks: ModelRef[] };
  builder: { primary: ModelRef; fallbacks: ModelRef[] };
  architect: { primary: ModelRef; fallbacks: ModelRef[] };
}

// ---------------------------------------------------------------------------
// Chat surface (provider-agnostic; shaped to fit Anthropic + OpenAI-compat)
// ---------------------------------------------------------------------------

export type ChatRole = "user" | "assistant";

export type ContentBlock =
  | { type: "text"; text: string }
  | { type: "tool_use"; id: string; name: string; input: unknown }
  | {
      type: "tool_result";
      toolUseId: string;
      content: string;
      isError?: boolean;
    };

export interface ChatMessage {
  role: ChatRole;
  content: ContentBlock[];
}

/** JSON Schema for tool inputs (object schema, additionalProperties false). */
export interface ToolSpec {
  name: string;
  description: string;
  inputSchema: Record<string, unknown>;
}

export interface ChatRequest {
  system: string;
  messages: ChatMessage[];
  tools: ToolSpec[];
  maxTokens: number;
  /**
   * Provider-interpreted effort/reasoning hint. Adapters map it to native
   * params (Anthropic: output_config.effort; others: best-effort or ignore).
   */
  effort?: "low" | "medium" | "high" | "xhigh" | "max";
  /**
   * Marks the stable prefix boundary for prompt caching. Adapters that
   * support caching place a cache breakpoint after `system` and after the
   * message at this index (if >= 0).
   */
  cacheBreakpointMessageIndex?: number;
}

/** Streaming events emitted by a ChatModel during one completion. */
export type StreamEvent =
  | { type: "text_delta"; text: string }
  | { type: "thinking_delta"; text: string }
  | { type: "tool_use"; id: string; name: string; input: unknown }
  | { type: "usage"; usage: TokenUsage }
  | { type: "done"; stopReason: StopReason };

export type StopReason =
  | "end_turn"
  | "tool_use"
  | "max_tokens"
  | "refusal"
  | "error";

export interface TokenUsage {
  inputTokens: number;
  outputTokens: number;
  cacheReadTokens: number;
  cacheWriteTokens: number;
}

export const ZERO_USAGE: TokenUsage = {
  inputTokens: 0,
  outputTokens: 0,
  cacheReadTokens: 0,
  cacheWriteTokens: 0,
};

export function addUsage(a: TokenUsage, b: TokenUsage): TokenUsage {
  return {
    inputTokens: a.inputTokens + b.inputTokens,
    outputTokens: a.outputTokens + b.outputTokens,
    cacheReadTokens: a.cacheReadTokens + b.cacheReadTokens,
    cacheWriteTokens: a.cacheWriteTokens + b.cacheWriteTokens,
  };
}

/** One model, ready to stream completions. Produced by a ProviderAdapter. */
export interface ChatModel {
  readonly ref: ModelRef;
  stream(req: ChatRequest, signal?: AbortSignal): AsyncIterable<StreamEvent>;
  /** Rough client-side token estimate (chars/4 fallback is acceptable). */
  estimateTokens(text: string): number;
}

export interface ProviderAdapter {
  readonly id: string;
  /** Model ids this adapter can serve (static list from config is fine). */
  models(): string[];
  create(modelId: string): ChatModel;
}

export interface ProviderRegistry {
  getModel(ref: ModelRef): ChatModel;
  /** All configured models with their pricing (for `cox models`). */
  listModels(): { ref: ModelRef; pricing: ModelPricing | null }[];
}

// ---------------------------------------------------------------------------
// Pricing
// ---------------------------------------------------------------------------

/** USD per million tokens. `null` = unknown (ledger records tokens only). */
export interface ModelPricing {
  inputPerMTok: number;
  outputPerMTok: number;
  cacheReadPerMTok: number | null;
  cacheWritePerMTok: number | null;
  /** Where these numbers came from + date checked. */
  source: string;
}

export function computeCostUsd(u: TokenUsage, p: ModelPricing): number {
  const M = 1_000_000;
  return (
    (u.inputTokens * p.inputPerMTok) / M +
    (u.outputTokens * p.outputPerMTok) / M +
    (u.cacheReadTokens * (p.cacheReadPerMTok ?? p.inputPerMTok)) / M +
    (u.cacheWriteTokens * (p.cacheWritePerMTok ?? p.inputPerMTok)) / M
  );
}

// ---------------------------------------------------------------------------
// Routing
// ---------------------------------------------------------------------------

/** What kind of work is being routed. */
export type TaskKind =
  | "chat" // free-form interactive turn
  | "oneshot" // cox explain / cox suggest
  | "spec-requirements"
  | "spec-design"
  | "spec-tasks" // generating the task list from a design
  | "spec-task-exec" // executing one implementation task
  | "hook" // agent hook automation
  | "classify"; // the router's own classification calls

export interface RoutingInput {
  kind: TaskKind;
  /** The prompt/task text being routed (for classification). */
  text: string;
  /** 1 (mechanical) .. 5 (novel/architectural). From spec task metadata. */
  complexityHint?: number;
  /** Estimated tokens already in context for this call. */
  contextTokens: number;
  /** Explicit user override, e.g. `/model architect` or `cox -m scout`. */
  userOverrideTier?: Tier;
  /** Tier forced by a hook (PreModelCall) or agent-hook declaration. */
  hookOverrideTier?: Tier;
  sessionId: string;
  specName?: string;
  taskId?: string;
}

export interface RoutingDecision {
  tier: Tier;
  model: ModelRef;
  /** Human-readable reasons, shown verbatim to the user. Order matters. */
  reasons: string[];
  /** Pre-call estimate for visibility; never used for billing. */
  estimate: {
    inputTokens: number;
    estOutputTokens: number;
    estCostUsd: number | null;
  };
  /** Set when this decision replaced an earlier one mid-task. */
  escalatedFrom?: Tier;
  /** True when the budget governor degraded the tier. */
  degradedByBudget?: boolean;
}

/** Signals the agent loop feeds back to the router while a task runs. */
export type EscalationSignal =
  | { type: "tool_error_streak"; count: number }
  | { type: "verification_failed"; attempts: number } // tests/build failed after edit
  | { type: "model_stuck"; evidence: string } // repeated identical tool calls
  | { type: "model_requested_help" } // model output matched an "I can't" pattern
  | { type: "context_overflow"; contextTokens: number };

export interface Router {
  route(input: RoutingInput): Promise<RoutingDecision>;
  /**
   * Called mid-task with accumulated signals. Returns a new decision when the
   * router wants to escalate/de-escalate, else null (keep current model).
   */
  reconsider(
    current: RoutingDecision,
    input: RoutingInput,
    signals: EscalationSignal[],
  ): Promise<RoutingDecision | null>;
}

// ---------------------------------------------------------------------------
// Ledger & budgets
// ---------------------------------------------------------------------------

export interface LedgerEntry {
  ts: string; // ISO 8601
  sessionId: string;
  kind: TaskKind;
  specName?: string;
  taskId?: string;
  tier: Tier;
  model: ModelRef;
  usage: TokenUsage;
  costUsd: number | null; // null when pricing unknown
  /** RoutingDecision.reasons at call time (for the audit trail). */
  routingReasons: string[];
  escalatedFrom?: Tier;
  durationMs: number;
}

export interface LedgerQuery {
  sessionId?: string;
  specName?: string;
  since?: string; // ISO 8601
  tier?: Tier;
}

export interface LedgerSummary {
  entries: number;
  usage: TokenUsage;
  costUsd: number;
  byTier: Partial<Record<Tier, { calls: number; usage: TokenUsage; costUsd: number }>>;
  byModel: Record<string, { calls: number; usage: TokenUsage; costUsd: number }>;
  /**
   * What the same calls would have cost if every call had run on the
   * architect tier's primary model — the "savings vs all-architect" number.
   */
  baselineArchitectCostUsd: number;
}

export interface BudgetConfig {
  sessionUsd?: number;
  sessionTokens?: number;
  specUsd?: number;
  /** Warn at this fraction of any budget (default 0.8). */
  warnAt: number;
  /** When true, hard-stop model calls at 100% until the user extends. */
  hardStop: boolean;
}

export type BudgetLevel = "ok" | "warn" | "exceeded";

export interface BudgetState {
  level: BudgetLevel;
  spentUsd: number;
  spentTokens: number;
  limitUsd?: number;
  limitTokens?: number;
  /** Which scope tripped: "session" | "spec". */
  scope?: string;
}

export interface Ledger {
  record(entry: LedgerEntry): Promise<void>;
  query(q: LedgerQuery): Promise<LedgerEntry[]>;
  summary(q: LedgerQuery): Promise<LedgerSummary>;
  budgetState(sessionId: string, specName?: string): Promise<BudgetState>;
}

// ---------------------------------------------------------------------------
// Tools & permissions
// ---------------------------------------------------------------------------

export type PermissionMode = "default" | "acceptEdits" | "plan" | "yolo";

export interface PermissionRequest {
  toolName: string;
  /** One-line human description, e.g. `bash: rm -rf dist/`. */
  summary: string;
  /** Unified diff preview for file edits, command text for bash, etc. */
  detail?: string;
}

export type PermissionDecision = "allow" | "allowAlways" | "deny";

export interface ToolContext {
  cwd: string;
  sessionId: string;
  /** Run-level abort; long-running tools (bash, subprocesses) must observe it. */
  signal?: AbortSignal;
  /** Resolves permission requests (TUI prompt, or policy in yolo/CI mode). */
  requestPermission(req: PermissionRequest): Promise<PermissionDecision>;
  emit(event: AgentEvent): void;
}

export interface Tool {
  spec: ToolSpec;
  /** Return null when the call needs no permission under the given mode. */
  permissionFor(
    input: unknown,
    mode: PermissionMode,
  ): PermissionRequest | null;
  execute(input: unknown, ctx: ToolContext): Promise<ToolResult>;
}

export interface ToolResult {
  content: string;
  isError: boolean;
}

export interface ToolRegistry {
  list(): Tool[];
  get(name: string): Tool | undefined;
}

// ---------------------------------------------------------------------------
// Agent loop
// ---------------------------------------------------------------------------

export interface AgentTask {
  kind: TaskKind;
  prompt: string;
  /** Fully-assembled system prompt (steering already included, stable-first). */
  system: string;
  /** Prior conversation to continue, empty for fresh tasks. */
  history: ChatMessage[];
  cwd: string;
  sessionId: string;
  specName?: string;
  taskId?: string;
  complexityHint?: number;
  userOverrideTier?: Tier;
  maxTurns?: number; // default 40 tool-use turns
}

export interface AgentRunResult {
  finalText: string;
  history: ChatMessage[];
  usage: TokenUsage;
  costUsd: number;
  stopReason: StopReason | "max_turns" | "budget_stop" | "aborted";
}

/**
 * The agent loop. Streams AgentEvents while running; the returned promise
 * resolves with the aggregate result. Implemented by @cox/agent; consumed by
 * cli, spec engine, and hooks engine.
 */
export interface AgentRunner {
  run(
    task: AgentTask,
    onEvent: (e: AgentEvent) => void,
    signal?: AbortSignal,
  ): Promise<AgentRunResult>;
}

// ---------------------------------------------------------------------------
// Spec coding (Kiro-style: requirements → design → tasks)
// ---------------------------------------------------------------------------

export type SpecPhase = "requirements" | "design" | "tasks" | "execution";

export type SpecPhaseStatus = "missing" | "draft" | "approved";

export type SpecTaskStatus = "pending" | "in_progress" | "done" | "blocked";

export interface SpecTask {
  id: string; // "1", "2.1", ...
  title: string;
  /** Requirement ids this task satisfies, e.g. ["R1.2", "R3.1"]. */
  requirements: string[];
  /** 1 (mechanical) .. 5 (architectural). Drives routing. */
  complexity: number;
  status: SpecTaskStatus;
}

export interface SpecState {
  name: string;
  createdAt: string;
  phases: Record<Exclude<SpecPhase, "execution">, SpecPhaseStatus>;
  tasks: SpecTask[];
  /** Approvals log: phase, ISO timestamp. */
  approvals: { phase: SpecPhase; at: string }[];
}

export interface SpecEngine {
  create(name: string, idea: string): Promise<SpecState>;
  load(name: string): Promise<SpecState | null>;
  list(): Promise<SpecState[]>;
  /** Generate/regenerate the current draft phase document via the agent. */
  generate(name: string, phase: SpecPhase): Promise<SpecState>;
  approve(name: string, phase: SpecPhase): Promise<SpecState>;
  /** Execute one task (or the next pending one when taskId omitted). */
  runTask(name: string, taskId?: string): Promise<SpecState>;
}

// ---------------------------------------------------------------------------
// Steering docs
// ---------------------------------------------------------------------------

export type SteeringInclusion = "always" | "fileMatch" | "manual";

export interface SteeringDoc {
  name: string; // file stem, e.g. "product", "tech"
  path: string;
  inclusion: SteeringInclusion;
  /** Glob for fileMatch inclusion, e.g. "src/api/**". */
  fileMatchPattern?: string;
  body: string;
  /** Estimated tokens (for /context display + budget warnings). */
  tokens: number;
  /** True for imported CLAUDE.md / AGENTS.md / copilot-instructions. */
  imported: boolean;
}

export interface SteeringSelection {
  /** Docs to concatenate into the system prompt, stable order. */
  systemDocs: SteeringDoc[];
  /** fileMatch docs injected as context blocks in the user turn. */
  contextDocs: SteeringDoc[];
  totalTokens: number;
}

export interface SteeringStore {
  loadAll(cwd: string): Promise<SteeringDoc[]>;
  /**
   * Choose docs for a task. `touchedFiles` drives fileMatch inclusion;
   * `manualNames` comes from /steer use or #name references in the prompt.
   */
  select(
    docs: SteeringDoc[],
    touchedFiles: string[],
    manualNames: string[],
  ): SteeringSelection;
}

// ---------------------------------------------------------------------------
// Hooks
// ---------------------------------------------------------------------------

export type HookEventName =
  | "SessionStart"
  | "UserPromptSubmit"
  | "PreToolUse"
  | "PostToolUse"
  | "PreModelCall"
  | "PostModelCall"
  | "SpecPhaseChange"
  | "TaskComplete"
  | "Stop"
  | "SessionEnd";

/** JSON payload piped to command hooks on stdin. */
export interface HookPayload {
  event: HookEventName;
  sessionId: string;
  cwd: string;
  /** Event-specific data (tool name/input, decision, spec state, ...). */
  data: Record<string, unknown>;
}

export interface CommandHookConfig {
  event: HookEventName;
  /** Regex matched against tool name (PreToolUse/PostToolUse) or "*". */
  matcher?: string;
  command: string; // run via $SHELL -c
  timeoutMs?: number; // default 30_000
}

/** Kiro-style agent hook: an automation that enqueues an agent task. */
export interface AgentHookConfig {
  name: string;
  /** fileSave fires from the in-session watcher; manual via `cox hook run`. */
  trigger: { type: "fileSave"; pattern: string } | { type: "manual" };
  /** Tier the automation runs on. Default "scout" — automations stay cheap. */
  tier: Tier;
  prompt: string;
}

export interface HookOutcome {
  hook: string; // command string or agent hook name
  /** block: exit code 2 — feed stderr back to the model / cancel the action. */
  action: "continue" | "block";
  stderr?: string;
  /** Parsed stdout JSON when the hook emitted any (may carry overrides). */
  output?: { tierOverride?: Tier; [k: string]: unknown };
}

export interface HookEngine {
  fire(payload: HookPayload): Promise<HookOutcome[]>;
  agentHooks(): AgentHookConfig[];
}

// ---------------------------------------------------------------------------
// Agent events (single stream the TUI renders; ledger listens for usage)
// ---------------------------------------------------------------------------

export type AgentEvent =
  | { type: "session_started"; sessionId: string; cwd: string }
  | { type: "user_prompt"; text: string }
  | {
      type: "routing_decision";
      decision: RoutingDecision;
      kind: TaskKind;
      taskId?: string;
    }
  | { type: "model_call_started"; model: ModelRef; tier: Tier }
  | { type: "text_delta"; text: string }
  | { type: "thinking_delta"; text: string }
  | { type: "tool_call_started"; id: string; name: string; summary: string }
  | { type: "permission_request"; request: PermissionRequest }
  | {
      type: "tool_call_finished";
      id: string;
      name: string;
      isError: boolean;
      resultPreview: string;
    }
  | {
      type: "model_call_finished";
      model: ModelRef;
      usage: TokenUsage;
      costUsd: number | null;
      stopReason: StopReason;
      durationMs: number;
    }
  | { type: "escalation"; from: Tier; to: Tier; reasons: string[] }
  | { type: "budget_alert"; state: BudgetState }
  | {
      type: "spec_event";
      specName: string;
      phase: SpecPhase;
      status: string;
      taskId?: string;
      tasksDone?: number;
      tasksTotal?: number;
    }
  | { type: "hook_fired"; event: HookEventName; outcomes: HookOutcome[] }
  | { type: "agent_message"; text: string }
  | { type: "error"; message: string }
  | {
      type: "turn_done";
      usage: TokenUsage;
      costUsd: number;
      stopReason?: AgentRunResult["stopReason"];
    };

// ---------------------------------------------------------------------------
// Session control (TUI ⇄ engine boundary)
// ---------------------------------------------------------------------------

/**
 * Implemented by @cox/cli; consumed by @cox/tui. The TUI never imports
 * engines directly — it renders AgentEvents and calls this interface.
 */
export interface SessionController {
  submitPrompt(text: string): void;
  /** Slash commands: "/spec", "/steer", "/ledger", "/model", "/context"... */
  submitCommand(command: string, args: string[]): void;
  resolvePermission(decision: PermissionDecision): void;
  interrupt(): void;
  readonly sessionId: string;
}

export interface SessionSnapshot {
  sessionId: string;
  currentTier: Tier;
  currentModel: ModelRef | null;
  usage: TokenUsage;
  costUsd: number;
  budget: BudgetState;
  activeSpec?: { name: string; phase: SpecPhase; tasksDone: number; tasksTotal: number };
}
