#!/usr/bin/env bash
# Install a user-local `cox` launcher that points at this monorepo.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
BIN_DIR="${COX_BIN_DIR:-$HOME/.local/bin}"
LAUNCHER="$BIN_DIR/cox"

mkdir -p "$BIN_DIR"

cat > "$LAUNCHER" <<EOF
#!/usr/bin/env bash
# Auto-generated by coxswain scripts/install-cox.sh
set -euo pipefail
export COXSWAIN_ROOT="${ROOT}"
exec pnpm --dir "${ROOT}" exec tsx packages/cli/src/main.ts "\$@"
EOF
chmod +x "$LAUNCHER"

echo "installed: $LAUNCHER"
echo "COXSWAIN_ROOT=$ROOT"
if ! echo ":$PATH:" | grep -q ":$BIN_DIR:"; then
  echo "add to PATH: export PATH=\"$BIN_DIR:\$PATH\""
fi
echo "try: cox --help"
echo "     cox cx doctor"
echo "     cox --cwd ~/TelcoCXOS cx status telco-core"
